services:
  app-alunos:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db-alunos

  db-alunos:
    image: postgres:15
    environment:
      - POSTGRE_DB_URL=${POSTGRE_DB_URL}
      - POSTGRE_DB_USER=${POSTGRE_DB_PASSWORD}
      - POSTGRE_DB_PASSWORD=${POSTGRE_DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "5432:5432"