FROM maven:3.8.4-eclipse-temurin-17 AS build
LABEL maintainer="Matheus Cristophi"
WORKDIR /app

COPY target/gerenciador-de-alunos-0.0.1-SNAPSHOT.jar /app/gerenciadorAlunos.jar

COPY src /app/src

RUN mvn clean package -DskipTests

EXPOSE 8080

ENV POSTGRE_DB_URL=jdbc:postgresql://db_container_name:5432/nome_do_banco

ENV POSTGRE_DB_USER=db_user

ENV POSTGRE_DB_PASSWORD=db_password

ENV JWT_SECRET=your_jwt_secret_key

ENTRYPOINT ["java", "-jar", "gerenciadorAlunos.jar"]