spring.application.name=gerenciadorDeAlunos

spring.datasource.url=jdbc:postgresql://localhost:5432/cadastro
spring.datasource.username=postgres
spring.datasource.password=Matheus.909
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true